version: '3.7'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es1
    environment:
      - node.name=es1
      - cluster.name=es-cluster
      - discovery.seed_hosts=es1,host.docker.internal:9301,host.docker.internal:9302
      - cluster.initial_master_nodes=es1,es2,es3
      - path.data=/usr/share/elasticsearch/data
      - path.logs=/usr/share/elasticsearch/logs
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc:
        soft: 1024000
        hard: 1024000
      nofile:
        soft: 1024000
        hard: 1024000
    sysctls:
      net.core.somaxconn: 65000
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cat/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    volumes:
      - es-data1:/usr/share/elasticsearch/data:rw
      - es-logs1:/usr/share/elasticsearch/logs:rw
#      - ${FULL-PATH-DATA}:/usr/share/elasticsearch/data:rw
#      - ${FULL-PATH-LOG}:/usr/share/elasticsearch/logs:rw
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge

volumes:
  es-data1:
    driver: local
  es-logs1:
    driver: local

networks:
  es-bridge:
    driver: bridge

